disabled_rules:
    - type_name
    - trailing_whitespace
    - identifier_name
    - force_cast
    - comment_spacing
    - mark
    - line_length
    - vertical_whitespace
    - trailing_newline
    - blanket_disable_command
